### ISSUE TITLE
Speedup drafter.js parsing

### ISSUE THREAD

**Issue by Art4** [apiaryio/drafter#308]
Drafter.js needs extremly much time to parse multiple-nested data in objects. I've build a simple API Blueprint file to demonstrate the problem:

```md
FORMAT: 1A
HOST: https://example.com

# Test API

description

# Group Test

## Error Test [/test/error]

### Retrieve an error [GET]
+ Response 200

    + Attributes

        + data (object)
            + attributes (object)
                + key1: `value` (string) - A string
                + key2: `value` (string) - A string
                + key3: `value` (string) - A string
                + key4: `value` (string) - A string
                + key5: `value` (string) - A string
                + key6: `value` (string) - A string
                + key7: `value` (string) - A string
                + key8: `value` (string) - A string
                + key9: `value` (string) - A string
                + key10: `value` (string) - A string
                + key11: `value` (string) - A string
                + key12: `value` (string) - A string
                + key13: `value` (string) - A string
                + key14: `value` (string) - A string
                + key15: `value` (string) - A string
                + key16: `value` (string) - A string
                + key17: `value` (string) - A string
                + key18: `value` (string) - A string
                + key19: `value` (string) - A string
                + key20: `value` (string) - A string
```

Drafter.js needs up to 2 minutes on my machine to parse this file. If you add more endpoints for listing, POST, PUT, and so on, the parsing process needs an incredible long time.

Any ideas how to speed up the parsing?

**Comment by w-vi** [comment]
Hi @Art4 we are very well aware of this situation and have couple of ideas how to improve it significantly but there's not enough time at the moment. Without changes in the drafter C++ code it can't be speed up much. I have few tips on getting it bit faster just by different compilation flags but these changes are not 100% robust so if you have really need it you can give it a try and rebuild it., let me know if you are interested and I'll create a gist with the necessary changes.

**Comment by Art4** [comment]
@w-vi Thank you very much but I'm not familiar with C++ and building. At the moment I'm using protagonist (inside Drakov) but wanted to switch to drafter.js to get rid of the python dependency. I wasn't sure if this issue was known because I couldn't find an issue about that.

I'm sorry that I can not help but would like to stay up to date.

**Comment by w-vi** [comment]
@Art4 Sorry that I can't offer better solution now but will keep this open so once I get to it I'll update it here.

**Comment by w-vi** [comment]
@Art4  so we have done some big changes and drafter.js is now separated in https://github.com/apiaryio/drafter.js and has been improved quite a bit too. hasn't been released yet but the speed has improved significantly so you can give it a try and try to build it from master or use the attached file. With the release we are waiting for some C++ fixes in drafter but should happen quite soon™
[drafter.nomem.js.tar.gz](https://github.com/apiaryio/drafter/files/311845/drafter.nomem.js.tar.gz)

**Comment by Art4** [comment]
Thanks for the update.

I've tried to use drafter.js 2.4.0, but [it isn't published on npmjs.org](https://github.com/apiaryio/drafter.js/issues/45) yet.

I've also tried your attached file, but it seems to been broken.

```
.\node_modules\drafter.js\lib\drafter.nomem.js:1
UncaughtException",function(ex){if(!(ex instanceof ExitStatus))throw ex}),Modul
                                                                    ^
TypeError: undefined is not a function
    at Pointer_stringify (.\node_modules\drafter.js\lib\drafter.nomem.js:1:2921)
    at Object.Module.parse (.\node_modules\drafter.js\lib\drafter.nomem.js:47:5989)
    at .lib\parse\blueprint.js:13:17
    at .\node_modules\async\lib\async.js:718:13
    at iterate (.\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (.\node_modules\async\lib\async.js:281:9)
    at _parallel (.\node_modules\async\lib\async.js:717:9)
    at Object.async.series (.\node_modules\async\lib\async.js:739:9)
    at .\lib\middleware\route-map.js:23:15
    at f (.\node_modules\glob\node_modules\once\once.js:17:25)

```

**Comment by w-vi** [comment]
@Art4 drafter.js 2.4.0 was released npmjs.org about half an hour ago, please can you give it a try?

**Comment by Art4** [comment]
Thanks, I've tried it again but got an error while `node-gyp rebuild` on Windows and Ubuntu. Am I missed something?

Error on Win7:

```
$ npm install drafter.js
npm WARN excluding symbolic link build\out\Release\obj.target\libdrafterjs.a -> [...]\node_modules\drafter.js\drafter.js\build\out\Release\libdrafterjs.a

> drafter.js@2.4.0 install [...]\node_modules\drafter.js
> node-gyp rebuild

[...]\node_modules\drafter.js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp: ext\drafter\ext\snowcrash\common.gypi not found (cwd: [...]\node_modules\drafter.js) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd [...]\node_modules\drafter.js
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "drafter.js"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! drafter.js@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drafter.js@2.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the drafter.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls drafter.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [...]\npm-debug.log
```

Error on Ubuntu:

```
$ npm install drafter.js
npm WARN excluding symbolic link build/out/Release/obj.target/libdrafterjs.a -> [...]/node_modules/drafter.js/drafter.js/build/out/Release/libdrafterjs.a

> drafter.js@2.4.0 install [...]/node_modules/drafter.js
> node-gyp rebuild

gyp: ext/drafter/ext/snowcrash/common.gypi not found (cwd: [...]/node_modules/drafter.js) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Linux 4.2.0-41-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd [...]/node_modules/drafter.js
gyp ERR! node -v v0.12.15
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.2.0-41-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "drafter.js"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! drafter.js@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the drafter.js@2.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the drafter.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs drafter.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls drafter.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [...]/npm-debug.log

```

**Comment by kylef** [comment]
@Art4 There was an issue with the drafter.js 2.4.0 package and we will be releasing an update shortly (https://github.com/apiaryio/drafter.js/pull/51).

**Comment by Art4** [comment]
Thanks. :+1:

**Comment by Art4** [comment]
@kylef Installation of v2.4.1 still fails...

```
$ npm install drafter.js

> drafter.js@2.4.1 install [...]\node_modules\drafter.js
> node-gyp rebuild

[...]\node_modules\drafter.js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp: binding.gyp not found (cwd: [...]\node_modules\drafter.js) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd [...]\node_modules\drafter.js
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "drafter.js"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! drafter.js@2.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drafter.js@2.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the drafter.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls drafter.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [...]\npm-debug.log
```

**Comment by w-vi** [comment]
@Art4 `npm` has some funny features/issues like https://github.com/npm/read-package-json/issues/61 which we are hitting so we have found a workaround for it and another version, hopefully completely fixed version is on its way.

**Comment by Art4** [comment]
So this makes my failing builds already a 3-times-dependency bug. :see_no_evil: :laughing: 

Hang on guys, you're doing an awesome job. :+1:

**Comment by Art4** [comment]
Thanks, `npm install` works again.

But I get an error if I use it:

```
$ ./node_modules/drakov/drakov -f ./apiary.apib -p 3000
[INFO] No configuration files found
[INFO] Loading configuration from CLI
   DRAKOV STARTED
[...]\node_modules\drakov\node_modules\drafter.js\lib\drafter.nomem.js:1
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));Mod
                                                                    ^
TypeError: undefined is not a function
    at Pointer_stringify ([...]\node_modules\drakov\node_modules\drafter.js\lib\drafter.nomem.js:1:13675)
    at Object.Module.parse ([...]\node_modules\drakov\node_modules\drafter.js\lib\drafter.nomem.js:20:7616)
    at [...]\node_modules\drakov\lib\parse\blueprint.js:13:17
    at [...]\node_modules\drakov\node_modules\async\lib\async.js:718:13
    at iterate ([...]\node_modules\drakov\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries ([...]\node_modules\drakov\node_modules\async\lib\async.js:281:9)
    at _parallel ([...]\node_modules\drakov\node_modules\async\lib\async.js:717:9)
    at Object.async.series ([...]\node_modules\drakov\node_modules\async\lib\async.js:739:9)
    at [...]\node_modules\drakov\lib\middleware\route-map.js:23:15
    at f ([...]\node_modules\drakov\node_modules\glob\node_modules\once\once.js:17:25)
```

I cannot determine if this is a problem with drafter.js or drakov.

**Comment by w-vi** [comment]
@Art4  do you get the error when you try to parse the blueprint using this? https://github.com/apiaryio/drafter.js/blob/master/scripts/parse.js

**Comment by Art4** [comment]
You can take a look how drakov uses drafter.js here: https://github.com/Aconex/drakov/blob/master/lib/parse/blueprint.js#L13

Drakov provides a callback as third argument to `drafter.parse()`

**Comment by Art4** [comment]
I have changed the code so it parses the blueprint like in your example. But I get the same error as yesterday.

**Comment by w-vi** [comment]
@Art4 Can you please provide me with the failing blueprint? If you don't want to post it publicly please send it over by email to wvi@apiary.io

**Comment by Art4** [comment]
Oh, my bad. I hadn't think about thats maybe a problem with my blueprint. 

I will look for the failing part of the blueprint and will paste it here.

**Comment by Art4** [comment]
@w-vi I found the problem. I have german specific characters (ä,ö,ü,ß) in my blueprint. Wenn I remove/change them drafter.js parses the blueprint like a charm.

Here are some examples with the special characters in the response.

```
FORMAT: 1A
HOST: https://example.org

# Test-API

description

# Foo [/foo/bar]

Get data

## Retrieve the account stats [GET]
+ Response 200 (application/vnd.api+json)

    + Attributes

        + foo1: `barä` (string)
        + foo2: `barö` (string)
        + foo3: `barü` (string)
        + foo4: `barß` (string)
        + foo5: `bar` (string) - This is also bad ä
        + fö: `bar` (string) - This too
```

**Comment by w-vi** [comment]
@Art4  Thanks a lot for digging it out, apparently you are not the only one.

I am closing this one in favor of https://github.com/apiaryio/drafter.js/issues/54 as it describes exactly what happens. I have a fix in place too.

**Comment by Art4** [comment]
Great! Thank you very much.
