### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by openreplyuk** [apiaryio/drafter#81]
I got the following error while trying to parse an apib file. See below. Can you please advise on this?

It looks like an app stack size is reached. Is there any way to increase app stack size globally?

RangeError: Maximum call stack size exceeded 
at /usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/inspect.js:200:5 
at Object.hasAnyMemberSections (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/inspect.js:208:5) 
at isObject (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/typeresolution.js:61:18) 
at resolveImplicitType (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/typeresolution.js:75:11) 
at /usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/typeresolution.js:126:14 
at simplifyTypeSpecification (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/typeresolution.js:41:12) 
at resolveType (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/typeresolution.js:121:10) 
at handleElement (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/formats/jsonschema-v4.js:533:10) 
at resolveProperty (/usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/formats/jsonschema-v4.js:46:10) 
at /usr/local/lib/node_modules/aglio/node_modules/drafter/node_modules/boutique/lib/formats/jsonschema-v4.js:61:12

**Comment by klokane** [comment]
It seems to be problem of aglio not drafter directly.
@danielgtaylor is it correct?

**Comment by pksunkara** [comment]
This is a problem with the default stack size of nodejs command when working on big blueprints. @openreplyuk Please increase your nodejs stack size and you should not see this.

**Comment by openreplyuk** [comment]
Solved increasing node stack size.
Thanks.
